# Arrays

In [2]:
from array import *

In [3]:
# Create an array 

my_array = array('i', [1, 2, 3, 4, 5])

print(my_array)

array('i', [1, 2, 3, 4, 5])


In [4]:
type(my_array)

array.array

In [5]:
# traverse through an array

for i in my_array:
    print(i)

1
2
3
4
5


In [7]:
# access individual elements indexes

print(my_array[3])

4


In [8]:
# append any value to the array using append()

my_array.append(25)

print(my_array)

array('i', [1, 2, 3, 4, 5, 25])


In [9]:
# insert vale in an array using insert()

my_array.insert(0, 30)

print(my_array)

array('i', [30, 1, 2, 3, 4, 5, 25])


In [11]:
# extend python array using extend()

my_array1 = array('i', [10, 11, 12])

my_array.extend(my_array1)
print(my_array)

array('i', [30, 1, 2, 3, 4, 5, 25, 10, 11, 12])


In [12]:
# add items from list into array using fromlist()

tempList = [20, 21, 22]

my_array.fromlist(tempList)
print(my_array)

array('i', [30, 1, 2, 3, 4, 5, 25, 10, 11, 12, 20, 21, 22])


In [14]:
# remove any array element using remove()

my_array.remove(22)
print(my_array)

array('i', [30, 1, 2, 3, 4, 5, 25, 10, 11, 12, 20, 21])


In [15]:
# remove last array element using pop()

my_array.pop()
print(my_array)

array('i', [30, 1, 2, 3, 4, 5, 25, 10, 11, 12, 20])


In [17]:
# fetch an element through its index using index()

my_array.index(11)
print(my_array.index(11))

8


In [18]:
# reverse a python array using reverse()

my_array.reverse()
print(my_array)

array('i', [20, 12, 11, 10, 25, 5, 4, 3, 2, 1, 30])


In [19]:
# get array buffer information through buffer_info() 

print(my_array.buffer_info())

(2371738645040, 11)


In [20]:
# check for number of occurences of an element using count()

my_array.append(11)
print(my_array)
my_array.count(11)

array('i', [20, 12, 11, 10, 25, 5, 4, 3, 2, 1, 30, 11])


2

In [24]:
# convert array to string using tostring()

str_array = my_array.tobytes()

ints = array('i')

ints.frombytes(str_array)
print(ints)
print(type(ints))

array('i', [20, 12, 11, 10, 25, 5, 4, 3, 2, 1, 30, 11])
<class 'array.array'>


In [26]:
# convert array to a python list with same elements using tolist() 

lst_array = my_array.tolist()
print(type(lst_array))
print(lst_array)

<class 'list'>
[20, 12, 11, 10, 25, 5, 4, 3, 2, 1, 30, 11]


In [27]:
# Slice elements from an array 

print(my_array[1:4])

array('i', [12, 11, 10])


In [28]:
my_array

array('i', [20, 12, 11, 10, 25, 5, 4, 3, 2, 1, 30, 11])

# Two Dimensional Arrays

In [1]:
# create a 2 dim array

import numpy as np 

arr = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])

print(type(arr))

<class 'numpy.ndarray'>


In [2]:
arr

array([[11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

In [3]:
# insertion 

new_arr = np.insert(arr, 0, [[1, 2, 3, 4]], axis=1)

print(new_arr)

[[ 1 11 15 10  6]
 [ 2 10 14 11  5]
 [ 3 12 17 12  8]
 [ 4 15 18 14  9]]


In [4]:
new_arr1 = np.insert(arr, 0, [[1, 2, 3, 4]], axis=0)

print(new_arr1)

[[ 1  2  3  4]
 [11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [5]:
new_arr2 = np.insert(arr, 1, [[4, 5, 6, 7]], axis=0)

print(new_arr2)

[[11 15 10  6]
 [ 4  5  6  7]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [7]:
new_arr3 = np.append(arr, [[4, 5, 6, 7]], axis=0)
new_arr3

array([[11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9],
       [ 4,  5,  6,  7]])

In [9]:
# accessing element from 2 dim array

def access_elements(arr, rowindex, colindex):
    if rowindex >= len(arr) and colindex >= len(arr[0]):
        print("Incorrect index")
    else:
        print(arr[rowindex, colindex])

access_elements(arr, 1, 2)

11


In [13]:
print(arr)
access_elements(arr, 2, 3)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
8


In [16]:
# traversal of 2 dim array

def traverse_array(arr):
    for i in range(len(arr)):
        for j in range(len(arr[0])):
            print(arr[i][j])


print(arr)

print(".................")

traverse_array(arr)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
.................
11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9
